### PR TITLE
Invalid content

### PR DESCRIPTION
**Pull request by kaitj**
Handles previously found issue of a server error in the case of invalid content being uploaded (#71). This PR adds code to check for this by checking if a version is found. Also adds in a new test case for this particular error.

Additionally, removes an old error that is no longer raised!

### CODE REVIEW

**Comment by kaitj** [comment]
Looking at it again, I agree that we can probably have a better check in place, but I also see 3 cases where an error is going to get thrown if it passes the first check:
1) Invalid content (either line 129 or line 152)
2) Too few rows (if the content doesn't have the same number of rows line 159)
3) Too many rows (as you mention the error at line 120)

I think (1) or (3) is most likely to occur in the case it passes that first test, in which case you'll probably be checking the .fcsv manually. We could write a check to properly validate the file, but I'm not sure how we go about implementing that without checking the file line by line (essentially what we are doing already anyways). Any ideas? (In the mean time I am going to mock up a fake .fcsv with a proper header and see what happens)

**Comment by tkkuehn** [comment]
I think we're already handling all those kinds of errors, I just mean that the csv reader won't know what to do when it starts parsing at line 120 if the file has no CSV-like structure, which will lead to an exception we're not handling. See the second last example [here](https://docs.python.org/3/library/csv.html) for an example of how to handle that kind of case.

**Comment by kaitj** [comment]
Ahh I see what you mean now. Can discuss some more during the call today!

**Comment by kaitj** [comment]
Changes from Tristan to handling valid header with invalid content looks good! Merging the PR and closing

**Pull request merged**
