### PR TITLE
Use push-protected for releases

### PR DESCRIPTION
**Pull request by tkkuehn**
## Proposed changes

The release workflow fails to push changes to pyproject.toml because `master` is protected. This uses the same fix earlier applied to the CI workflow.

## Types of changes

What types of changes does your code introduce? Put an `x` in the boxes that apply

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionalitiy)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (if none of the other choices apply)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [ ] Code has been run through [`black`](https://github.com/psf/black) with the `-l 79` flag.
- [ ] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/PULL_REQUEST_TEMPLATE.md)_

### CODE REVIEW

**Comment by tkkuehn** [comment]
I guess maybe this should use `branch: master`?

**Review by kaitj — APPROVED** [review]

**Review by kaitj — APPROVED** [review]

**Comment by kaitj** [comment]
> I guess maybe this should use `branch: master`?

It use to default to that, unless that function has changed.

**Comment by tkkuehn** [comment]
Ah I didn't realize

**Comment by kaitj** [comment]
Actually it is better to explictly state it - looks like they changed it to default to `main` with the new gh default.

**Pull request merged**
