### PR TITLE
Add new template fiducials

### PR DESCRIPTION
**Pull request by tkkuehn**
## Proposed changes

Add all the templates from https://github.com/ataha24/afids-data/tree/main/data/templates to the validator

## Types of changes

What types of changes does your code introduce? Put an `x` in the boxes that apply

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionalitiy)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (if none of the other choices apply)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [ ] Code has been run through [`black`](https://github.com/psf/black) with the `-l 79` flag.
- [ ] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/PULL_REQUEST_TEMPLATE.md)_

### CODE REVIEW

**Review by kaitj — APPROVED** [review]
Looks good to me, should I merge this in or are we waiting on anything?

**Comment by tkkuehn** [comment]
Note: After talking to Alaa, we want to keep the existing versions of Agile12v2016 and Colin27, but update PD25, so that's what's in the PR now. If it still looks good we can merge

**Comment by kaitj** [comment]
Still looks good to me. And yeah, we can merge - I forgot the workflow will deploy to the test application and we would need to manually run the deployment to production app

**Comment by tkkuehn** [comment]
Yeah after merging I'll take a look at the test version then deploy. Thanks!

**Pull request merged**
