### PR TITLE
Fix broken template FCSVs

### PR DESCRIPTION
**Pull request by tkkuehn**
## Proposed changes

Add a test for template FCSV validity and (eventually) fix the broken templates

## Types of changes

What types of changes does your code introduce? Put an `x` in the boxes that apply

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionalitiy)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (if none of the other choices apply)

## Checklist

Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you are unsure about any of the choices, don't hesitate to ask!

- [ ] Changes have been tested to ensure that fix is effective or that a feature works.
- [ ] Changes pass the unit tests
- [ ] Code has been run through [`black`](https://github.com/psf/black) with the `-l 79` flag.
- [ ] I have included necessary documentation or comments (as necessary)
- [ ] Any dependent changes have been merged and published

## Notes
All PRs will undergo the unit testing before being reviewed. You may be requested to explain or make additional changes before the PR is accepted.

_PR template was adopted from [appium](https://github.com/appium/appium/blob/master/.github/PULL_REQUEST_TEMPLATE.md)_

### CODE REVIEW

**Review by kaitj — COMMENTED** [review]
Couple of things that we probably want to consider as well.

1. Right now all templates are for humans, but I think we are close to adding in non-human templates as well. Should this be a separate test (might be related to point 2) or should this single test be more agnostic?

2. How would we handle testing in the event that the fiducials are not named the same across species?

**Comment by tkkuehn** [comment]
>     1. Right now all templates are for humans, but I think we are close to adding in non-human templates as well. Should this be a separate test (might be related to point 2) or should this single test be more agnostic?

I think this should either be a separate test or this test should be extended when we add non-human templates.

>     2. How would we handle testing in the event that the fiducials are not named the same across species?

The validation logic in `model.py` will need to handle that, and the tests should use the appropriate function for the templates they're testing.

**Comment by kaitj** [comment]
> I think this should either be a separate test or this test should be extended when we add non-human templates.

Fair - in this case, how would you feel about renaming `test_all_templates` to `test_human_templates` (line 8)?

> The validation logic in model.py will need to handle that, and the tests should use the appropriate function for the templates they're testing.

Ahh yeah, been a while forgot thats there. And we know it works for NHPs at least (I think fiducials are named the same).

Looks good to me otherwise.

**Comment by tkkuehn** [comment]
> How would you feel about renaming `test_all_templates` to `test_human_templates` (line 8)?

Done

**Review by kaitj — APPROVED** [review]

**Pull request merged**
